-- WITH TMP AS(
-- SELECT * FROM ONLINE_SALE
-- WHERE SALES_DATE BETWEEN TO_DATE('20220301', 'YYYYMMDD') AND TO_DATE('20220331', 'YYYYMMDD')

-- UNION ALL
    
-- SELECT OFFLINE_SALE_ID
--         ,   NULL                     
--         ,   PRODUCT_ID
--         ,   SALES_AMOUNT
--         ,   SALES_DATE
--   FROM OFFLINE_SALE
--  WHERE SALES_DATE BETWEEN TO_DATE('20220301', 'YYYYMMDD') AND TO_DATE('20220331', 'YYYYMMDD')
-- )

-- SELECT      TO_CHAR(SALES_DATE,'YYYY-MM-DD') SALES_DATE
--         ,   PRODUCT_ID
--         ,   USER_ID
--         ,   SALES_AMOUNT
-- FROM        TMP
-- ORDER BY    1 ASC, 2 ASC, 3 ASC


-- SELECT TO_CHAR(A.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE, A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
--   FROM ONLINE_SALE A, OFFLINE_SALE B
--  WHERE A.SALES_DATE=B.SALES_DATE(+) 
--    AND A.PRODUCT_ID=B.PRODUCT_ID(+)
--    AND A.SALES_AMOUNT = B.SALES_AMOUNT(+)
--    AND TO_CHAR(A.SALES_DATE,'YYYY-MM-DD') BETWEEN '2022-03-01' AND '2022-03-31'
--  ORDER BY A.SALES_DATE, A.PRODUCT_ID,USER_ID

SELECT TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') SALES_DATE, A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
FROM(
    SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'MM') = '03'

    UNION

    SELECT NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'MM') = '03'
) A
ORDER BY 1,2,3;
