-- 코드를 입력하세요
SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
-- MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES) AS max_fav
  FROM (SELECT FOOD_TYPE
               , FAVORITES
               , REST_ID
               , REST_NAME
               , RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS max_fav
         FROM REST_INFO
        ) B
 WHERE B.max_fav = 1
 ORDER BY B.FOOD_TYPE DESC