-- 코드를 입력하세요
SELECT B.HOUR, NVL(A.COUNT, 0) AS COUNT
  FROM (
        SELECT EXTRACT (HOUR FROM CAST(DATETIME AS TIMESTAMP)) HOUR , COUNT(*) COUNT
          FROM ANIMAL_OUTS 
         GROUP BY EXTRACT (HOUR FROM CAST(DATETIME AS TIMESTAMP))
       ) A
       , (
          SELECT LEVEL - 1 AS HOUR 
            FROM DUAL CONNECT BY LEVEL <= 24
       ) B
 WHERE A.HOUR(+) = B.HOUR
 ORDER BY HOUR
